<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container33SHffv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container33SHffv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container33SHffv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container33SHffv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container33SHffv\App_KernelDevDebugContainer([
    'container.build_hash' => '33SHffv',
    'container.build_id' => '480a74a5',
    'container.build_time' => 1713446626,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container33SHffv');
