<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container631UTPO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container631UTPO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container631UTPO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container631UTPO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container631UTPO\App_KernelDevDebugContainer([
    'container.build_hash' => '631UTPO',
    'container.build_id' => 'c37e0cb0',
    'container.build_time' => 1722172973,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container631UTPO');
